### PR TITLE
The code is somewhat organized, featuring various components.

### PR DESCRIPTION
**Pull request by mutasim77**
Heyy, what do you think about this?

### CODE REVIEW

**Comment by mutasim77** [comment]
Give me your feedback

**Comment by NamanGarg2075** [comment]
> Heyy, what do you think about this?

Have broken links in your contribution kindly look into it and fix it then i will review it because without it `yarn start` command gives error and failed to load website

Kindly make sure to check website locally by running `yarn start` command

And yeah you added Kotlin image but look at the taglink of that image it is still (HYPERTEXT MARKUP LANGUAGE) 
Leave Image part to me because i have that template so in future i will add that

**Comment by mutasim77** [comment]
yep done, u can check it. Also for now put just placeholder for image

**Comment by NamanGarg2075** [comment]
> yep done, u can check it. Also for now put just placeholder for image

Bro kindly fix broken links issue by testing it locally using `yarn start`

**Comment by mutasim77** [comment]
> 

sorry bro, idk what broken links you're talking about. cuz i'm running project locally and testing it, there's no issue

**Comment by NamanGarg2075** [comment]
> > 
> 
> sorry bro, idk what broken links you're talking about. cuz i'm running project locally and testing it, there's no issue

try running `yarn build` you will see an error of `onbrokenLinks`

**Comment by NamanGarg2075** [comment]
> > 
> 
> sorry bro, idk what broken links you're talking about. cuz i'm running project locally and testing it, there's no issue

I have fixed that error (That error is because of python's path in python card component)

Thanks for this contribution

In future make sure to look these checks for no error if in case there is error click on details to see what's the error
image

**Review by NamanGarg2075 — APPROVED** [review]

**Comment by mutasim77** [comment]
okay, thank you for explaining.

**Pull request merged**
