### PR TITLE
Added about Lists

### PR DESCRIPTION
**Pull request by mutasim77**

### CODE REVIEW

**Comment by NamanGarg2075** [comment]
nice work

but it would be better if you add outputs in BrowserWindow component

**Comment by mutasim77** [comment]
can i know more about BrowserWindow component?

**Comment by NamanGarg2075** [comment]
are you interested in adding that feature or not?

**Comment by NamanGarg2075** [comment]
> can i know more about BrowserWindow component?

image

you can find this BrowserComponent under  src>components folder

**Comment by NamanGarg2075** [comment]
> can i know more about BrowserWindow component?

to add this feature first you need to change file extension to `.mdx` from `.md`

then import this component to `.mdx` file by adding `import BrowserWindow from '@site/src/components/BrowserWindow';`

next cover output section in `<BrowserWindow> ... </BrowserWindow>`

### **Cleared?**

**Comment by mutasim77** [comment]
yeah thx, lemme try

**Comment by mutasim77** [comment]
DONE ✅

**Comment by NamanGarg2075** [comment]
> DONE ✅

bro you need to add that component to only outputs not the whole document 
image

like this output

**Comment by mutasim77** [comment]
got it

**Comment by NamanGarg2075** [comment]
> got it

i will add that 
thanks for adding list docs

**Pull request merged**
